/**
 * GoTripza Route Pairs — 50 high-traffic flight routes
 * Powers /[locale]/routes/[slug] SEO pages
 */

export type RoutePair = {
  slug: string;
  fromIata: string;
  toIata: string;
  fromNameEn: string;
  fromNameAr: string;
  toNameEn: string;
  toNameAr: string;
  fromCountryEn: string;
  fromCountryAr: string;
  toCountryEn: string;
  toCountryAr: string;
  avgPriceUsd: number;      // avg round-trip economy
  durationHours: number;    // flight duration in decimal hours
  airlines: string[];       // main carriers
  tipsEn: string;
  tipsAr: string;
  toDestSlug: string;       // matches DESTINATION slug for internal links (or "")
};

export const ROUTE_PAIRS: RoutePair[] = [
  // ── From Dubai (DXB) ────────────────────────────────────────────────────
  {
    slug: "dubai-to-london",
    fromIata: "DXB", toIata: "LHR",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "London", toNameAr: "لندن",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "United Kingdom", toCountryAr: "المملكة المتحدة",
    avgPriceUsd: 520, durationHours: 7.5,
    airlines: ["Emirates", "British Airways", "flydubai"],
    tipsEn: "Emirates flies direct in under 7.5h — book 6-8 weeks ahead for the best fares, especially in summer when demand peaks.",
    tipsAr: "طيران الإمارات يطير مباشرة في أقل من 7.5 ساعات — احجز قبل 6-8 أسابيع للحصول على أفضل الأسعار خاصة في الصيف.",
    toDestSlug: "london",
  },
  {
    slug: "dubai-to-paris",
    fromIata: "DXB", toIata: "CDG",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "Paris", toNameAr: "باريس",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "France", toCountryAr: "فرنسا",
    avgPriceUsd: 540, durationHours: 7,
    airlines: ["Emirates", "Air France", "flydubai"],
    tipsEn: "Emirates operates daily nonstop flights. Avoid peak summer (Jul-Aug) and fashion weeks (Jan, Sep, Oct) for lower fares.",
    tipsAr: "الإمارات تشغل رحلات يومية مباشرة. تجنب ذروة الصيف (يوليو-أغسطس) وأسابيع الموضة للحصول على أسعار أفضل.",
    toDestSlug: "paris",
  },
  {
    slug: "dubai-to-bangkok",
    fromIata: "DXB", toIata: "BKK",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "Bangkok", toNameAr: "بانكوك",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "Thailand", toCountryAr: "تايلاند",
    avgPriceUsd: 380, durationHours: 6,
    airlines: ["Emirates", "Thai Airways", "flydubai", "Air Arabia"],
    tipsEn: "One of the most popular routes from the Gulf. November to February is the best time to visit Bangkok — book at least 2 months ahead.",
    tipsAr: "من أكثر الطرق شعبية من الخليج. نوفمبر حتى فبراير هو أفضل وقت لزيارة بانكوك — احجز قبل شهرين على الأقل.",
    toDestSlug: "bangkok",
  },
  {
    slug: "dubai-to-bali",
    fromIata: "DXB", toIata: "DPS",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "Bali", toNameAr: "بالي",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "Indonesia", toCountryAr: "إندونيسيا",
    avgPriceUsd: 450, durationHours: 8.5,
    airlines: ["Emirates", "Singapore Airlines", "Qatar Airways"],
    tipsEn: "Most flights connect through Singapore or Kuala Lumpur. June-August and July-September are Bali's dry season — ideal timing.",
    tipsAr: "معظم الرحلات تمر عبر سنغافورة أو كوالالمبور. يونيو-أغسطس وسبتمبر هو موسم الجفاف في بالي — أفضل وقت للزيارة.",
    toDestSlug: "bali",
  },
  {
    slug: "dubai-to-istanbul",
    fromIata: "DXB", toIata: "IST",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "Istanbul", toNameAr: "إسطنبول",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "Turkey", toCountryAr: "تركيا",
    avgPriceUsd: 340, durationHours: 4.5,
    airlines: ["Turkish Airlines", "Emirates", "flydubai", "Air Arabia"],
    tipsEn: "Turkish Airlines has excellent business class on this route. Spring (April-May) and autumn (September-October) offer the best Istanbul weather.",
    tipsAr: "الخطوط التركية لديها درجة أعمال ممتازة في هذا الطريق. الربيع (أبريل-مايو) والخريف (سبتمبر-أكتوبر) أفضل أوقات إسطنبول.",
    toDestSlug: "istanbul",
  },
  {
    slug: "dubai-to-tokyo",
    fromIata: "DXB", toIata: "NRT",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "Tokyo", toNameAr: "طوكيو",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "Japan", toCountryAr: "اليابان",
    avgPriceUsd: 620, durationHours: 9.5,
    airlines: ["Emirates", "Japan Airlines", "ANA", "Etihad"],
    tipsEn: "Emirates flies nonstop in just under 10h. Cherry blossom season (late March-April) is magical but book 3-4 months ahead.",
    tipsAr: "الإمارات تطير مباشرة في أقل من 10 ساعات. موسم أزهار الكرز (أواخر مارس-أبريل) ساحر لكن احجز قبل 3-4 أشهر.",
    toDestSlug: "tokyo",
  },
  {
    slug: "dubai-to-singapore",
    fromIata: "DXB", toIata: "SIN",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "Singapore", toNameAr: "سنغافورة",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "Singapore", toCountryAr: "سنغافورة",
    avgPriceUsd: 420, durationHours: 7,
    airlines: ["Singapore Airlines", "Emirates", "flydubai"],
    tipsEn: "Singapore Airlines offers one of the best economy products on this route. Singapore is a year-round destination with no bad season.",
    tipsAr: "تقدم سنغافورة إيرلاينز من أفضل تجارب الدرجة الاقتصادية على هذا الطريق. سنغافورة وجهة مثالية طوال السنة.",
    toDestSlug: "singapore",
  },
  {
    slug: "dubai-to-new-york",
    fromIata: "DXB", toIata: "JFK",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "New York", toNameAr: "نيويورك",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "USA", toCountryAr: "الولايات المتحدة",
    avgPriceUsd: 780, durationHours: 13.5,
    airlines: ["Emirates", "United Airlines", "American Airlines"],
    tipsEn: "Emirates operates the world's longest nonstop commercial flight (DXB-JFK). Book in winter for the lowest fares.",
    tipsAr: "طيران الإمارات يشغل أطول رحلة مباشرة تجارية في العالم (دبي-نيويورك). احجز في الشتاء للحصول على أقل الأسعار.",
    toDestSlug: "new-york",
  },
  {
    slug: "dubai-to-rome",
    fromIata: "DXB", toIata: "FCO",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "Rome", toNameAr: "روما",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "Italy", toCountryAr: "إيطاليا",
    avgPriceUsd: 480, durationHours: 6.5,
    airlines: ["Emirates", "ITA Airways", "flydubai"],
    tipsEn: "Spring (April-May) is peak season for Rome — book early. Summer is crowded but July evenings are beautiful for outdoor dining.",
    tipsAr: "الربيع (أبريل-مايو) هو الموسم الذهبي لروما — احجز مبكراً. الصيف مزدحم لكن أمسيات يوليو رائعة للمطاعم الخارجية.",
    toDestSlug: "rome",
  },
  {
    slug: "dubai-to-barcelona",
    fromIata: "DXB", toIata: "BCN",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "Barcelona", toNameAr: "برشلونة",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "Spain", toCountryAr: "إسبانيا",
    avgPriceUsd: 500, durationHours: 7,
    airlines: ["Emirates", "Vueling", "Iberia", "Air Arabia"],
    tipsEn: "May-June is ideal — warm enough for beaches but before the August crowds. Book Sagrada Familia tickets 3 months ahead.",
    tipsAr: "مايو-يونيو مثالي — دافئ للشواطئ قبل ازدحام أغسطس. احجز تذاكر Sagrada Familia قبل 3 أشهر.",
    toDestSlug: "barcelona",
  },
  {
    slug: "dubai-to-phuket",
    fromIata: "DXB", toIata: "HKT",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "Phuket", toNameAr: "بوكيت",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "Thailand", toCountryAr: "تايلاند",
    avgPriceUsd: 400, durationHours: 7,
    airlines: ["Emirates", "Thai Airways", "Air Arabia", "flydubai"],
    tipsEn: "November to April is dry season — pristine beaches and calm seas. Avoid May-October monsoon season unless you want lower prices.",
    tipsAr: "نوفمبر حتى أبريل موسم الجفاف — شواطئ نظيفة وبحر هادئ. تجنب موسم الأمطار مايو-أكتوبر إلا إذا كنت تريد أسعاراً أقل.",
    toDestSlug: "phuket",
  },
  {
    slug: "dubai-to-maldives",
    fromIata: "DXB", toIata: "MLE",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "Maldives", toNameAr: "المالديف",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "Maldives", toCountryAr: "المالديف",
    avgPriceUsd: 380, durationHours: 4,
    airlines: ["Emirates", "flydubai", "Maldivian"],
    tipsEn: "Book your resort and seaplane transfer together — resorts in Maldives require separate domestic flights or speedboats to reach.",
    tipsAr: "احجز المنتجع والمروحية المائية معاً — المنتجعات في المالديف تحتاج رحلات داخلية منفصلة أو زوارق سريعة للوصول إليها.",
    toDestSlug: "maldives",
  },
  {
    slug: "dubai-to-muscat",
    fromIata: "DXB", toIata: "MCT",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "Muscat", toNameAr: "مسقط",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "Oman", toCountryAr: "عُمان",
    avgPriceUsd: 120, durationHours: 1.3,
    airlines: ["Oman Air", "flydubai", "Air Arabia"],
    tipsEn: "One of the shortest international routes from Dubai — under 1.5h. October to April is ideal; avoid summer heat above 40°C.",
    tipsAr: "من أقصر الطرق الدولية من دبي — أقل من 1.5 ساعة. أكتوبر حتى أبريل مثالي؛ تجنب حرارة الصيف التي تتجاوز 40 درجة.",
    toDestSlug: "muscat",
  },
  {
    slug: "dubai-to-cairo",
    fromIata: "DXB", toIata: "CAI",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "Cairo", toNameAr: "القاهرة",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "Egypt", toCountryAr: "مصر",
    avgPriceUsd: 250, durationHours: 3.5,
    airlines: ["Emirates", "EgyptAir", "flydubai", "Air Arabia"],
    tipsEn: "October to April is the best time for Cairo — pleasant weather for the Pyramids. Summer is scorching but prices drop significantly.",
    tipsAr: "أكتوبر حتى أبريل أفضل وقت للقاهرة — طقس لطيف لزيارة الأهرامات. الصيف حار جداً لكن الأسعار تنخفض بشكل ملحوظ.",
    toDestSlug: "cairo",
  },
  {
    slug: "dubai-to-kuala-lumpur",
    fromIata: "DXB", toIata: "KUL",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "Kuala Lumpur", toNameAr: "كوالالمبور",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "Malaysia", toCountryAr: "ماليزيا",
    avgPriceUsd: 390, durationHours: 7.5,
    airlines: ["Emirates", "Malaysia Airlines", "AirAsia"],
    tipsEn: "Malaysia has no bad season but March-October has less rain. Great value destination — KL is one of Southeast Asia's most affordable capitals.",
    tipsAr: "ماليزيا ليس لها موسم سيئ لكن مارس-أكتوبر أقل أمطاراً. وجهة ذات قيمة ممتازة — كوالالمبور من أرخص عواصم جنوب شرق آسيا.",
    toDestSlug: "kuala-lumpur",
  },
  {
    slug: "dubai-to-amsterdam",
    fromIata: "DXB", toIata: "AMS",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "Amsterdam", toNameAr: "أمستردام",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "Netherlands", toCountryAr: "هولندا",
    avgPriceUsd: 560, durationHours: 7,
    airlines: ["KLM", "Emirates", "flydubai"],
    tipsEn: "Tulip season (mid-April to mid-May) is spectacular but crowded. KLM offers excellent connections with their Dubai partnership.",
    tipsAr: "موسم التوليب (منتصف أبريل حتى منتصف مايو) رائع لكن مزدحم. KLM تقدم اتصالات ممتازة مع شراكتها في دبي.",
    toDestSlug: "amsterdam",
  },
  {
    slug: "dubai-to-vienna",
    fromIata: "DXB", toIata: "VIE",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "Vienna", toNameAr: "فيينا",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "Austria", toCountryAr: "النمسا",
    avgPriceUsd: 520, durationHours: 6.5,
    airlines: ["Austrian Airlines", "Emirates", "flydubai"],
    tipsEn: "Christmas markets (Dec) and summer music festivals make Vienna magical year-round. Austrian Airlines has excellent service on this route.",
    tipsAr: "أسواق الكريسماس (ديسمبر) ومهرجانات الموسيقى الصيفية تجعل فيينا ساحرة طوال العام. الخطوط النمساوية لديها خدمة ممتازة.",
    toDestSlug: "vienna",
  },
  {
    slug: "dubai-to-prague",
    fromIata: "DXB", toIata: "PRG",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "Prague", toNameAr: "براغ",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "Czech Republic", toCountryAr: "جمهورية التشيك",
    avgPriceUsd: 490, durationHours: 6.5,
    airlines: ["Czech Airlines", "Emirates", "Wizz Air"],
    tipsEn: "Prague is stunning in spring and Christmas markets in December are world-famous. One of Europe's most affordable capitals.",
    tipsAr: "براغ رائعة في الربيع وأسواق الكريسماس في ديسمبر ذات شهرة عالمية. إحدى أرخص العواصم الأوروبية.",
    toDestSlug: "prague",
  },
  {
    slug: "dubai-to-seoul",
    fromIata: "DXB", toIata: "ICN",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "Seoul", toNameAr: "سيول",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "South Korea", toCountryAr: "كوريا الجنوبية",
    avgPriceUsd: 580, durationHours: 9,
    airlines: ["Korean Air", "Emirates", "Asiana Airlines"],
    tipsEn: "Spring (March-May) for cherry blossoms and autumn (Sept-Nov) for stunning foliage — both are ideal. Korean Air's A380 service is exceptional.",
    tipsAr: "الربيع (مارس-مايو) لأزهار الكرز والخريف (سبتمبر-نوفمبر) للأوراق الملونة — كلاهما مثالي. خدمة Korean Air A380 استثنائية.",
    toDestSlug: "seoul",
  },
  {
    slug: "dubai-to-marrakech",
    fromIata: "DXB", toIata: "RAK",
    fromNameEn: "Dubai", fromNameAr: "دبي",
    toNameEn: "Marrakech", toNameAr: "مراكش",
    fromCountryEn: "UAE", fromCountryAr: "الإمارات",
    toCountryEn: "Morocco", toCountryAr: "المغرب",
    avgPriceUsd: 420, durationHours: 7.5,
    airlines: ["Royal Air Maroc", "Emirates", "Air Arabia Maroc"],
    tipsEn: "March-May and September-November are ideal. Avoid Ramadan if you want full restaurant access. Book riads 2-3 months ahead.",
    tipsAr: "مارس-مايو وسبتمبر-نوفمبر مثالية. تجنب رمضان إذا كنت تريد الوصول الكامل للمطاعم. احجز الرياض قبل 2-3 أشهر.",
    toDestSlug: "marrakech",
  },
  // ── From Riyadh (RUH) ───────────────────────────────────────────────────
  {
    slug: "riyadh-to-london",
    fromIata: "RUH", toIata: "LHR",
    fromNameEn: "Riyadh", fromNameAr: "الرياض",
    toNameEn: "London", toNameAr: "لندن",
    fromCountryEn: "Saudi Arabia", fromCountryAr: "المملكة العربية السعودية",
    toCountryEn: "United Kingdom", toCountryAr: "المملكة المتحدة",
    avgPriceUsd: 650, durationHours: 7,
    airlines: ["Saudia", "British Airways", "flyadeal"],
    tipsEn: "Saudia and British Airways both fly direct. Summer (July-August) demand from the Gulf is very high — book 2+ months ahead for these months.",
    tipsAr: "السعودية وبريتيش إيرويز تطيران مباشرة. الطلب صيفاً (يوليو-أغسطس) من الخليج مرتفع جداً — احجز قبل شهرين أو أكثر.",
    toDestSlug: "london",
  },
  {
    slug: "riyadh-to-istanbul",
    fromIata: "RUH", toIata: "IST",
    fromNameEn: "Riyadh", fromNameAr: "الرياض",
    toNameEn: "Istanbul", toNameAr: "إسطنبول",
    fromCountryEn: "Saudi Arabia", fromCountryAr: "المملكة العربية السعودية",
    toCountryEn: "Turkey", toCountryAr: "تركيا",
    avgPriceUsd: 320, durationHours: 3.5,
    airlines: ["Turkish Airlines", "Saudia", "Pegasus"],
    tipsEn: "One of the most popular routes from Saudi Arabia. Turkish Airlines offers excellent value with their frequent RUH-IST service.",
    tipsAr: "من أكثر الطرق شعبية من السعودية. الخطوط التركية تقدم قيمة ممتازة مع خدمتها المتكررة بين الرياض وإسطنبول.",
    toDestSlug: "istanbul",
  },
  {
    slug: "riyadh-to-cairo",
    fromIata: "RUH", toIata: "CAI",
    fromNameEn: "Riyadh", fromNameAr: "الرياض",
    toNameEn: "Cairo", toNameAr: "القاهرة",
    fromCountryEn: "Saudi Arabia", fromCountryAr: "المملكة العربية السعودية",
    toCountryEn: "Egypt", toCountryAr: "مصر",
    avgPriceUsd: 220, durationHours: 2.5,
    airlines: ["Saudia", "EgyptAir", "flyadeal"],
    tipsEn: "Very high frequency route — multiple daily flights. EgyptAir and Saudia both offer competitive prices. Great winter getaway from Riyadh.",
    tipsAr: "طريق عالي التردد — رحلات يومية متعددة. مصر للطيران والسعودية تقدمان أسعاراً تنافسية. وجهة شتوية رائعة من الرياض.",
    toDestSlug: "cairo",
  },
  {
    slug: "riyadh-to-paris",
    fromIata: "RUH", toIata: "CDG",
    fromNameEn: "Riyadh", fromNameAr: "الرياض",
    toNameEn: "Paris", toNameAr: "باريس",
    fromCountryEn: "Saudi Arabia", fromCountryAr: "المملكة العربية السعودية",
    toCountryEn: "France", toCountryAr: "فرنسا",
    avgPriceUsd: 680, durationHours: 6.5,
    airlines: ["Saudia", "Air France", "flyadeal"],
    tipsEn: "Saudia and Air France operate direct service. Paris visa (Schengen) takes 2-3 weeks — apply well in advance from Riyadh.",
    tipsAr: "السعودية وإير فرانس تشغلان خدمة مباشرة. تأشيرة باريس (شنغن) تستغرق 2-3 أسابيع — قدم الطلب مبكراً من الرياض.",
    toDestSlug: "paris",
  },
  {
    slug: "riyadh-to-bangkok",
    fromIata: "RUH", toIata: "BKK",
    fromNameEn: "Riyadh", fromNameAr: "الرياض",
    toNameEn: "Bangkok", toNameAr: "بانكوك",
    fromCountryEn: "Saudi Arabia", fromCountryAr: "المملكة العربية السعودية",
    toCountryEn: "Thailand", toCountryAr: "تايلاند",
    avgPriceUsd: 450, durationHours: 8,
    airlines: ["Saudia", "Thai Airways", "flyadeal"],
    tipsEn: "Most flights go via Dubai or Bahrain. November-March is the golden season for Bangkok — book holiday period flights 3 months ahead.",
    tipsAr: "معظم الرحلات تمر عبر دبي أو البحرين. نوفمبر-مارس هو الموسم الذهبي لبانكوك — احجز رحلات فترة العطل قبل 3 أشهر.",
    toDestSlug: "bangkok",
  },
  {
    slug: "riyadh-to-bali",
    fromIata: "RUH", toIata: "DPS",
    fromNameEn: "Riyadh", fromNameAr: "الرياض",
    toNameEn: "Bali", toNameAr: "بالي",
    fromCountryEn: "Saudi Arabia", fromCountryAr: "المملكة العربية السعودية",
    toCountryEn: "Indonesia", toCountryAr: "إندونيسيا",
    avgPriceUsd: 520, durationHours: 10,
    airlines: ["Saudia", "Emirates", "Qatar Airways"],
    tipsEn: "Bali is visa-free for Saudi nationals (30 days). Dry season (May-October) is best. Budget for a premium resort — Bali's luxury resorts are world-class.",
    tipsAr: "بالي بدون تأشيرة للمواطنين السعوديين (30 يوماً). موسم الجفاف (مايو-أكتوبر) الأفضل. خطط لميزانية المنتجع الفاخر — منتجعات بالي على مستوى عالمي.",
    toDestSlug: "bali",
  },
  {
    slug: "riyadh-to-kuala-lumpur",
    fromIata: "RUH", toIata: "KUL",
    fromNameEn: "Riyadh", fromNameAr: "الرياض",
    toNameEn: "Kuala Lumpur", toNameAr: "كوالالمبور",
    fromCountryEn: "Saudi Arabia", fromCountryAr: "المملكة العربية السعودية",
    toCountryEn: "Malaysia", toCountryAr: "ماليزيا",
    avgPriceUsd: 480, durationHours: 9,
    airlines: ["Malaysia Airlines", "Saudia", "AirAsia"],
    tipsEn: "Malaysia is Muslim-majority and halal food is everywhere — very comfortable for Saudi travelers. No visa needed for Saudi nationals.",
    tipsAr: "ماليزيا دولة مسلمة والطعام الحلال في كل مكان — مريحة جداً للمسافرين السعوديين. لا تأشيرة مطلوبة للمواطنين السعوديين.",
    toDestSlug: "kuala-lumpur",
  },
  {
    slug: "riyadh-to-amsterdam",
    fromIata: "RUH", toIata: "AMS",
    fromNameEn: "Riyadh", fromNameAr: "الرياض",
    toNameEn: "Amsterdam", toNameAr: "أمستردام",
    fromCountryEn: "Saudi Arabia", fromCountryAr: "المملكة العربية السعودية",
    toCountryEn: "Netherlands", toCountryAr: "هولندا",
    avgPriceUsd: 690, durationHours: 7,
    airlines: ["KLM", "Saudia"],
    tipsEn: "KLM flies direct from Riyadh. Amsterdam is a Schengen gateway — your visa covers all 26 Schengen countries. Apply at least 4 weeks before travel.",
    tipsAr: "KLM تطير مباشرة من الرياض. أمستردام بوابة شنغن — تأشيرتها تغطي 26 دولة شنغن. قدم الطلب قبل 4 أسابيع على الأقل من السفر.",
    toDestSlug: "amsterdam",
  },
  {
    slug: "riyadh-to-dubai",
    fromIata: "RUH", toIata: "DXB",
    fromNameEn: "Riyadh", fromNameAr: "الرياض",
    toNameEn: "Dubai", toNameAr: "دبي",
    fromCountryEn: "Saudi Arabia", fromCountryAr: "المملكة العربية السعودية",
    toCountryEn: "UAE", toCountryAr: "الإمارات",
    avgPriceUsd: 150, durationHours: 2,
    airlines: ["flydubai", "Saudia", "Air Arabia", "flyadeal"],
    tipsEn: "One of the world's busiest short-haul routes — dozens of daily flights. Book same-day for as low as $80 one-way on flydubai or Air Arabia.",
    tipsAr: "من أكثر طرق الرحلات القصيرة ازدحاماً في العالم — عشرات الرحلات اليومية. احجز في نفس اليوم بأقل من 300 ريال ذهاباً على flydubai أو Air Arabia.",
    toDestSlug: "dubai",
  },
  {
    slug: "riyadh-to-barcelona",
    fromIata: "RUH", toIata: "BCN",
    fromNameEn: "Riyadh", fromNameAr: "الرياض",
    toNameEn: "Barcelona", toNameAr: "برشلونة",
    fromCountryEn: "Saudi Arabia", fromCountryAr: "المملكة العربية السعودية",
    toCountryEn: "Spain", toCountryAr: "إسبانيا",
    avgPriceUsd: 700, durationHours: 7.5,
    airlines: ["Saudia", "Iberia", "Vueling"],
    tipsEn: "Most flights connect via Madrid or London. May and September are the best months — warm, less crowded, and better value than summer.",
    tipsAr: "معظم الرحلات تمر عبر مدريد أو لندن. مايو وسبتمبر أفضل الأشهر — دافئ وأقل ازدحاماً وقيمة أفضل من الصيف.",
    toDestSlug: "barcelona",
  },
  // ── From Jeddah (JED) ───────────────────────────────────────────────────
  {
    slug: "jeddah-to-istanbul",
    fromIata: "JED", toIata: "IST",
    fromNameEn: "Jeddah", fromNameAr: "جدة",
    toNameEn: "Istanbul", toNameAr: "إسطنبول",
    fromCountryEn: "Saudi Arabia", fromCountryAr: "المملكة العربية السعودية",
    toCountryEn: "Turkey", toCountryAr: "تركيا",
    avgPriceUsd: 280, durationHours: 3,
    airlines: ["Turkish Airlines", "Saudia", "Pegasus"],
    tipsEn: "Turkish Airlines operates multiple daily flights from Jeddah. No visa needed for Saudi nationals. April-May and September-October are ideal seasons.",
    tipsAr: "الخطوط التركية تشغل رحلات يومية متعددة من جدة. لا تأشيرة مطلوبة للمواطنين السعوديين. أبريل-مايو وسبتمبر-أكتوبر مواسم مثالية.",
    toDestSlug: "istanbul",
  },
  {
    slug: "jeddah-to-london",
    fromIata: "JED", toIata: "LHR",
    fromNameEn: "Jeddah", fromNameAr: "جدة",
    toNameEn: "London", toNameAr: "لندن",
    fromCountryEn: "Saudi Arabia", fromCountryAr: "المملكة العربية السعودية",
    toCountryEn: "United Kingdom", toCountryAr: "المملكة المتحدة",
    avgPriceUsd: 620, durationHours: 7,
    airlines: ["Saudia", "British Airways"],
    tipsEn: "Saudia and British Airways fly nonstop. June-August is peak Saudi season for London — fares can double. Book December trips for better value.",
    tipsAr: "السعودية وبريتيش إيرويز تطيران مباشرة. يونيو-أغسطس ذروة الموسم السعودي للندن — الأسعار قد تتضاعف. احجز رحلات ديسمبر لقيمة أفضل.",
    toDestSlug: "london",
  },
  {
    slug: "jeddah-to-cairo",
    fromIata: "JED", toIata: "CAI",
    fromNameEn: "Jeddah", fromNameAr: "جدة",
    toNameEn: "Cairo", toNameAr: "القاهرة",
    fromCountryEn: "Saudi Arabia", fromCountryAr: "المملكة العربية السعودية",
    toCountryEn: "Egypt", toCountryAr: "مصر",
    avgPriceUsd: 200, durationHours: 2,
    airlines: ["EgyptAir", "Saudia", "Air Arabia"],
    tipsEn: "One of the busiest routes in the Arab world. Extremely competitive pricing — check Air Arabia for budget fares under $100 one-way.",
    tipsAr: "من أكثر الطرق ازدحاماً في العالم العربي. تسعير تنافسي جداً — تحقق من Air Arabia للأسعار الاقتصادية بأقل من 370 ريال ذهاباً.",
    toDestSlug: "cairo",
  },
  {
    slug: "jeddah-to-bangkok",
    fromIata: "JED", toIata: "BKK",
    fromNameEn: "Jeddah", fromNameAr: "جدة",
    toNameEn: "Bangkok", toNameAr: "بانكوك",
    fromCountryEn: "Saudi Arabia", fromCountryAr: "المملكة العربية السعودية",
    toCountryEn: "Thailand", toCountryAr: "تايلاند",
    avgPriceUsd: 420, durationHours: 8.5,
    airlines: ["Saudia", "Thai Airways", "flyadeal"],
    tipsEn: "Connects via Dubai or Bahrain. Thailand offers 30-day visa on arrival for Saudi nationals. Great winter destination from Jeddah.",
    tipsAr: "تمر عبر دبي أو البحرين. تايلاند تمنح تأشيرة عند الوصول 30 يوماً للمواطنين السعوديين. وجهة شتوية رائعة من جدة.",
    toDestSlug: "bangkok",
  },
  {
    slug: "jeddah-to-kuala-lumpur",
    fromIata: "JED", toIata: "KUL",
    fromNameEn: "Jeddah", fromNameAr: "جدة",
    toNameEn: "Kuala Lumpur", toNameAr: "كوالالمبور",
    fromCountryEn: "Saudi Arabia", fromCountryAr: "المملكة العربية السعودية",
    toCountryEn: "Malaysia", toCountryAr: "ماليزيا",
    avgPriceUsd: 450, durationHours: 9,
    airlines: ["Malaysia Airlines", "Saudia", "AirAsia"],
    tipsEn: "Malaysia Airlines offers direct service. As a Muslim-majority country, Malaysia is very welcoming for Saudi travelers — halal food, mosques, and no visa needed.",
    tipsAr: "ماليزيا إيرلاينز تقدم خدمة مباشرة. كدولة ذات أغلبية مسلمة، ماليزيا مرحبة جداً بالمسافرين السعوديين — طعام حلال ومساجد ولا تأشيرة.",
    toDestSlug: "kuala-lumpur",
  },
  {
    slug: "jeddah-to-bali",
    fromIata: "JED", toIata: "DPS",
    fromNameEn: "Jeddah", fromNameAr: "جدة",
    toNameEn: "Bali", toNameAr: "بالي",
    fromCountryEn: "Saudi Arabia", fromCountryAr: "المملكة العربية السعودية",
    toCountryEn: "Indonesia", toCountryAr: "إندونيسيا",
    avgPriceUsd: 500, durationHours: 10.5,
    airlines: ["Saudia", "Emirates", "Malaysia Airlines"],
    tipsEn: "Usually connects in Dubai or Kuala Lumpur. Indonesian rupiah is very favorable for Saudi travelers. 30-day visa on arrival available.",
    tipsAr: "تمر عادة عبر دبي أو كوالالمبور. الروبية الإندونيسية مفضلة جداً للمسافرين السعوديين. تأشيرة عند الوصول 30 يوماً متاحة.",
    toDestSlug: "bali",
  },
  {
    slug: "jeddah-to-antalya",
    fromIata: "JED", toIata: "AYT",
    fromNameEn: "Jeddah", fromNameAr: "جدة",
    toNameEn: "Antalya", toNameAr: "أنطاليا",
    fromCountryEn: "Saudi Arabia", fromCountryAr: "المملكة العربية السعودية",
    toCountryEn: "Turkey", toCountryAr: "تركيا",
    avgPriceUsd: 290, durationHours: 3,
    airlines: ["Turkish Airlines", "Saudia", "Pegasus"],
    tipsEn: "Antalya is a summer paradise — peak season May-October. All-inclusive resorts offer incredible value. No visa needed for Saudi nationals.",
    tipsAr: "أنطاليا جنة صيفية — الموسم المثالي مايو-أكتوبر. المنتجعات الشاملة تقدم قيمة استثنائية. لا تأشيرة مطلوبة للمواطنين السعوديين.",
    toDestSlug: "antalya",
  },
  {
    slug: "jeddah-to-amsterdam",
    fromIata: "JED", toIata: "AMS",
    fromNameEn: "Jeddah", fromNameAr: "جدة",
    toNameEn: "Amsterdam", toNameAr: "أمستردام",
    fromCountryEn: "Saudi Arabia", fromCountryAr: "المملكة العربية السعودية",
    toCountryEn: "Netherlands", toCountryAr: "هولندا",
    avgPriceUsd: 650, durationHours: 7.5,
    airlines: ["KLM", "Saudia"],
    tipsEn: "KLM and Saudia both offer direct service. Tulip season (April-May) is spectacular but crowded — book 3 months ahead.",
    tipsAr: "KLM والسعودية تقدمان خدمة مباشرة. موسم التوليب (أبريل-مايو) رائع لكن مزدحم — احجز قبل 3 أشهر.",
    toDestSlug: "amsterdam",
  },
  // ── From Cairo (CAI) ────────────────────────────────────────────────────
  {
    slug: "cairo-to-dubai",
    fromIata: "CAI", toIata: "DXB",
    fromNameEn: "Cairo", fromNameAr: "القاهرة",
    toNameEn: "Dubai", toNameAr: "دبي",
    fromCountryEn: "Egypt", fromCountryAr: "مصر",
    toCountryEn: "UAE", toCountryAr: "الإمارات",
    avgPriceUsd: 260, durationHours: 3.5,
    airlines: ["EgyptAir", "flydubai", "Emirates"],
    tipsEn: "Dozens of daily flights. flydubai offers the cheapest fares. UAE visa (30-day) is easily obtained online for Egyptian nationals.",
    tipsAr: "عشرات الرحلات اليومية. flydubai تقدم أرخص الأسعار. تأشيرة الإمارات (30 يوماً) تحصل عليها بسهولة إلكترونياً للمواطنين المصريين.",
    toDestSlug: "dubai",
  },
  {
    slug: "cairo-to-london",
    fromIata: "CAI", toIata: "LHR",
    fromNameEn: "Cairo", fromNameAr: "القاهرة",
    toNameEn: "London", toNameAr: "لندن",
    fromCountryEn: "Egypt", fromCountryAr: "مصر",
    toCountryEn: "United Kingdom", toCountryAr: "المملكة المتحدة",
    avgPriceUsd: 550, durationHours: 5.5,
    airlines: ["EgyptAir", "British Airways"],
    tipsEn: "EgyptAir flies direct. UK visa is required for Egyptian nationals — apply 8-10 weeks in advance. Summer demand is very high.",
    tipsAr: "مصر للطيران تطير مباشرة. تأشيرة بريطانيا مطلوبة للمواطنين المصريين — قدم الطلب قبل 8-10 أسابيع. الطلب صيفاً مرتفع جداً.",
    toDestSlug: "london",
  },
  {
    slug: "cairo-to-istanbul",
    fromIata: "CAI", toIata: "IST",
    fromNameEn: "Cairo", fromNameAr: "القاهرة",
    toNameEn: "Istanbul", toNameAr: "إسطنبول",
    fromCountryEn: "Egypt", fromCountryAr: "مصر",
    toCountryEn: "Turkey", toCountryAr: "تركيا",
    avgPriceUsd: 280, durationHours: 3,
    airlines: ["Turkish Airlines", "EgyptAir", "Pegasus"],
    tipsEn: "Turkish Airlines has multiple daily flights. No visa required for Egyptian nationals. Istanbul is perfect for 4-5 days from Cairo.",
    tipsAr: "الخطوط التركية لديها رحلات يومية متعددة. لا تأشيرة مطلوبة للمواطنين المصريين. إسطنبول مثالية لـ 4-5 أيام من القاهرة.",
    toDestSlug: "istanbul",
  },
  {
    slug: "cairo-to-paris",
    fromIata: "CAI", toIata: "CDG",
    fromNameEn: "Cairo", fromNameAr: "القاهرة",
    toNameEn: "Paris", toNameAr: "باريس",
    fromCountryEn: "Egypt", fromCountryAr: "مصر",
    toCountryEn: "France", toCountryAr: "فرنسا",
    avgPriceUsd: 480, durationHours: 5,
    airlines: ["Air France", "EgyptAir"],
    tipsEn: "Air France and EgyptAir both operate direct. Schengen visa required for Egyptian nationals — apply through the French consulate in Cairo.",
    tipsAr: "إير فرانس ومصر للطيران تشغلان رحلات مباشرة. تأشيرة شنغن مطلوبة للمصريين — قدم الطلب عبر القنصلية الفرنسية في القاهرة.",
    toDestSlug: "paris",
  },
  {
    slug: "cairo-to-riyadh",
    fromIata: "CAI", toIata: "RUH",
    fromNameEn: "Cairo", fromNameAr: "القاهرة",
    toNameEn: "Riyadh", toNameAr: "الرياض",
    fromCountryEn: "Egypt", fromCountryAr: "مصر",
    toCountryEn: "Saudi Arabia", toCountryAr: "المملكة العربية السعودية",
    avgPriceUsd: 220, durationHours: 2.5,
    airlines: ["EgyptAir", "Saudia", "flynas"],
    tipsEn: "One of the world's busiest routes by passenger volume. Saudi work visa or tourism visa required for Egyptians. Book well ahead for Eid holidays.",
    tipsAr: "من أكثر الطرق ازدحاماً في العالم من حيث حجم الركاب. تأشيرة عمل أو سياحة سعودية مطلوبة للمصريين. احجز مبكراً لعطلات العيد.",
    toDestSlug: "",
  },
  // ── From Doha (DOH) ─────────────────────────────────────────────────────
  {
    slug: "doha-to-london",
    fromIata: "DOH", toIata: "LHR",
    fromNameEn: "Doha", fromNameAr: "الدوحة",
    toNameEn: "London", toNameAr: "لندن",
    fromCountryEn: "Qatar", fromCountryAr: "قطر",
    toCountryEn: "United Kingdom", toCountryAr: "المملكة المتحدة",
    avgPriceUsd: 580, durationHours: 7,
    airlines: ["Qatar Airways", "British Airways"],
    tipsEn: "Qatar Airways is consistently rated one of the world's top airlines — their business class (Qsuite) is exceptional. Book 8-10 weeks ahead for best economy fares.",
    tipsAr: "Qatar Airways تُصنَّف باستمرار من أفضل شركات الطيران في العالم — درجة أعمالها (Qsuite) استثنائية. احجز قبل 8-10 أسابيع لأفضل أسعار الاقتصادية.",
    toDestSlug: "london",
  },
  {
    slug: "doha-to-bangkok",
    fromIata: "DOH", toIata: "BKK",
    fromNameEn: "Doha", fromNameAr: "الدوحة",
    toNameEn: "Bangkok", toNameAr: "بانكوك",
    fromCountryEn: "Qatar", fromCountryAr: "قطر",
    toCountryEn: "Thailand", toCountryAr: "تايلاند",
    avgPriceUsd: 380, durationHours: 6.5,
    airlines: ["Qatar Airways", "Thai Airways"],
    tipsEn: "Qatar Airways offers superb value on this route. Qatari nationals get 30-day visa on arrival in Thailand. November-March is peak season.",
    tipsAr: "Qatar Airways تقدم قيمة رائعة على هذا الطريق. المواطنون القطريون يحصلون على تأشيرة عند الوصول 30 يوماً في تايلاند. نوفمبر-مارس موسم الذروة.",
    toDestSlug: "bangkok",
  },
  {
    slug: "doha-to-bali",
    fromIata: "DOH", toIata: "DPS",
    fromNameEn: "Doha", fromNameAr: "الدوحة",
    toNameEn: "Bali", toNameAr: "بالي",
    fromCountryEn: "Qatar", fromCountryAr: "قطر",
    toCountryEn: "Indonesia", toCountryAr: "إندونيسيا",
    avgPriceUsd: 460, durationHours: 9,
    airlines: ["Qatar Airways"],
    tipsEn: "Qatar Airways often has surprisingly affordable fares to Bali from Doha. Book dry season (May-Oct) flights at least 2 months ahead.",
    tipsAr: "Qatar Airways غالباً ما تقدم أسعاراً رائعة إلى بالي من الدوحة. احجز رحلات موسم الجفاف (مايو-أكتوبر) قبل شهرين على الأقل.",
    toDestSlug: "bali",
  },
  {
    slug: "doha-to-istanbul",
    fromIata: "DOH", toIata: "IST",
    fromNameEn: "Doha", fromNameAr: "الدوحة",
    toNameEn: "Istanbul", toNameAr: "إسطنبول",
    fromCountryEn: "Qatar", fromCountryAr: "قطر",
    toCountryEn: "Turkey", toCountryAr: "تركيا",
    avgPriceUsd: 310, durationHours: 3.5,
    airlines: ["Qatar Airways", "Turkish Airlines"],
    tipsEn: "Both Qatar Airways and Turkish Airlines serve this route well. No visa needed for Qatari nationals in Turkey. Great 4-5 day getaway.",
    tipsAr: "كلتا Qatar Airways والخطوط التركية تخدمان هذا الطريق بشكل ممتاز. لا تأشيرة مطلوبة للمواطنين القطريين في تركيا. وجهة رائعة لـ 4-5 أيام.",
    toDestSlug: "istanbul",
  },
  {
    slug: "doha-to-paris",
    fromIata: "DOH", toIata: "CDG",
    fromNameEn: "Doha", fromNameAr: "الدوحة",
    toNameEn: "Paris", toNameAr: "باريس",
    fromCountryEn: "Qatar", fromCountryAr: "قطر",
    toCountryEn: "France", toCountryAr: "فرنسا",
    avgPriceUsd: 560, durationHours: 6.5,
    airlines: ["Qatar Airways", "Air France"],
    tipsEn: "Qatar Airways flies nonstop and their business class on this route is world-class. Schengen visa required for Qatari nationals.",
    tipsAr: "Qatar Airways تطير مباشرة وفئة الأعمال على هذا الطريق على مستوى عالمي. تأشيرة شنغن مطلوبة للمواطنين القطريين.",
    toDestSlug: "paris",
  },
  // ── From Kuwait (KWI) ───────────────────────────────────────────────────
  {
    slug: "kuwait-to-istanbul",
    fromIata: "KWI", toIata: "IST",
    fromNameEn: "Kuwait", fromNameAr: "الكويت",
    toNameEn: "Istanbul", toNameAr: "إسطنبول",
    fromCountryEn: "Kuwait", fromCountryAr: "الكويت",
    toCountryEn: "Turkey", toCountryAr: "تركيا",
    avgPriceUsd: 300, durationHours: 3.5,
    airlines: ["Turkish Airlines", "Kuwait Airways", "Pegasus"],
    tipsEn: "No visa required for Kuwaiti nationals in Turkey. Turkish Airlines has the most frequency from Kuwait City. Great year-round destination.",
    tipsAr: "لا تأشيرة مطلوبة للمواطنين الكويتيين في تركيا. الخطوط التركية لديها أعلى تردد من الكويت. وجهة رائعة طوال العام.",
    toDestSlug: "istanbul",
  },
  {
    slug: "kuwait-to-london",
    fromIata: "KWI", toIata: "LHR",
    fromNameEn: "Kuwait", fromNameAr: "الكويت",
    toNameEn: "London", toNameAr: "لندن",
    fromCountryEn: "Kuwait", fromCountryAr: "الكويت",
    toCountryEn: "United Kingdom", toCountryAr: "المملكة المتحدة",
    avgPriceUsd: 580, durationHours: 6.5,
    airlines: ["Kuwait Airways", "British Airways", "Emirates"],
    tipsEn: "Kuwait Airways flies direct to London Heathrow. Summer is peak season for Kuwaiti travelers to London. UK visa required.",
    tipsAr: "الخطوط الجوية الكويتية تطير مباشرة إلى هيثرو. الصيف هو ذروة موسم المسافرين الكويتيين إلى لندن. تأشيرة بريطانية مطلوبة.",
    toDestSlug: "london",
  },
  {
    slug: "kuwait-to-bangkok",
    fromIata: "KWI", toIata: "BKK",
    fromNameEn: "Kuwait", fromNameAr: "الكويت",
    toNameEn: "Bangkok", toNameAr: "بانكوك",
    fromCountryEn: "Kuwait", fromCountryAr: "الكويت",
    toCountryEn: "Thailand", toCountryAr: "تايلاند",
    avgPriceUsd: 360, durationHours: 7,
    airlines: ["Kuwait Airways", "Thai Airways", "Emirates"],
    tipsEn: "Connects via Dubai or Bahrain. Thailand's 30-day visa on arrival available for Kuwaiti nationals. November-March is ideal.",
    tipsAr: "تمر عبر دبي أو البحرين. تأشيرة تايلاند عند الوصول 30 يوماً متاحة للكويتيين. نوفمبر-مارس مثالي.",
    toDestSlug: "bangkok",
  },
  {
    slug: "kuwait-to-dubai",
    fromIata: "KWI", toIata: "DXB",
    fromNameEn: "Kuwait", fromNameAr: "الكويت",
    toNameEn: "Dubai", toNameAr: "دبي",
    fromCountryEn: "Kuwait", fromCountryAr: "الكويت",
    toCountryEn: "UAE", toCountryAr: "الإمارات",
    avgPriceUsd: 130, durationHours: 1.5,
    airlines: ["flydubai", "Kuwait Airways", "Air Arabia"],
    tipsEn: "Under 2 hours and dozens of daily options. flydubai and Air Arabia offer budget fares. Great for a quick 3-4 day Dubai trip.",
    tipsAr: "أقل من ساعتين وعشرات الخيارات اليومية. flydubai وAir Arabia يقدمان أسعاراً اقتصادية. رائع لرحلة دبي سريعة 3-4 أيام.",
    toDestSlug: "dubai",
  },
];

export function getRoutePair(slug: string): RoutePair | undefined {
  return ROUTE_PAIRS.find((r) => r.slug === slug);
}

export const ROUTE_SLUGS = ROUTE_PAIRS.map((r) => r.slug);
