import type { Locale } from "@/i18n/config";

type SeoCopy = {
  shortAnswer: string;
  quickSnapshot: string;
  destinationSnapshot: string;
  relatedPlanningLinks: string;
  faq: string;
  from: string;
  to: string;
  localCurrency: string;
  originCurrency: string;
  perPersonDay: string;
  tripLength: string;
  inDestinationBudget: string;
  bestFor: string;
  planWithRya: string;
  askRya: string;
  airportArrivalGuide: string;
  transferOptions: string;
  lateArrival: string;
  esimWifi: string;
  taxiCaution: string;
  travelGuideHub: string;
  aiSearchReady: string;
  editorialNote: string;
};

const EN: SeoCopy = {
  shortAnswer: "Short answer",
  quickSnapshot: "Quick planning snapshot",
  destinationSnapshot: "Destination snapshot",
  relatedPlanningLinks: "Related planning links",
  faq: "Frequently asked questions",
  from: "From",
  to: "To",
  localCurrency: "Local currency",
  originCurrency: "Origin currency",
  perPersonDay: "per person / day",
  tripLength: "Trip length",
  inDestinationBudget: "In-destination budget",
  bestFor: "Best for",
  planWithRya: "Plan with Rya",
  askRya: "Ask Rya",
  airportArrivalGuide: "Arrival-first airport guide",
  transferOptions: "Transfer options",
  lateArrival: "Late arrival",
  esimWifi: "eSIM and Wi-Fi",
  taxiCaution: "Taxi caution",
  travelGuideHub: "Travel guide hub",
  aiSearchReady: "AI-search ready travel guide",
  editorialNote:
    "Planning note: travel rules, insurance terms, safety conditions, transport prices, and mobile coverage can change. Use this guide as practical planning help and confirm critical details with official providers before booking.",
};

const COPIES: Partial<Record<Locale, Partial<SeoCopy>>> = {
  ar: {
    shortAnswer: "الإجابة المختصرة",
    quickSnapshot: "ملخص سريع",
    destinationSnapshot: "ملخص الوجهة",
    relatedPlanningLinks: "روابط تخطيط مرتبطة",
    faq: "أسئلة شائعة",
    from: "من",
    to: "إلى",
    localCurrency: "عملة الوجهة",
    originCurrency: "عملة السوق",
    perPersonDay: "لكل شخص / يوم",
    tripLength: "المدة",
    inDestinationBudget: "داخل الوجهة",
    bestFor: "مناسب لـ",
    planWithRya: "خطط مع ريا",
    askRya: "اسأل ريا",
    airportArrivalGuide: "دليل وصول سريع",
    transferOptions: "خيارات النقل",
    lateArrival: "الوصول المتأخر",
    esimWifi: "eSIM والإنترنت",
    taxiCaution: "تنبيه التاكسي",
    travelGuideHub: "مركز أدلة السفر",
    aiSearchReady: "دليل قابل للظهور في بحث AI",
    editorialNote:
      "ملاحظة تخطيط: قد تتغير القوانين، شروط التأمين، الأمان، أسعار المواصلات، وتغطية الشبكات. استخدم الدليل كمرجع عملي وتحقق من التفاصيل المهمة من الجهات الرسمية قبل الحجز.",
  },
  fr: {
    shortAnswer: "Réponse rapide",
    quickSnapshot: "Résumé de planification",
    destinationSnapshot: "Aperçu de la destination",
    relatedPlanningLinks: "Liens de planification",
    faq: "Questions fréquentes",
    from: "Depuis",
    to: "Vers",
    localCurrency: "Devise locale",
    originCurrency: "Devise de départ",
    perPersonDay: "par personne / jour",
    planWithRya: "Planifier avec Rya",
    airportArrivalGuide: "Guide d'arrivée à l'aéroport",
    aiSearchReady: "Guide optimisé pour la recherche IA",
    editorialNote:
      "Note de planification : les règles, assurances, conditions de sécurité, prix des transports et couvertures mobiles peuvent changer. Vérifiez les détails critiques auprès des sources officielles.",
  },
  de: {
    shortAnswer: "Kurzantwort",
    quickSnapshot: "Planungsüberblick",
    destinationSnapshot: "Reiseziel-Überblick",
    relatedPlanningLinks: "Verwandte Planungslinks",
    faq: "Häufige Fragen",
    from: "Ab",
    to: "Nach",
    localCurrency: "Lokale Währung",
    originCurrency: "Ausgangswährung",
    perPersonDay: "pro Person / Tag",
    planWithRya: "Mit Rya planen",
    airportArrivalGuide: "Ankunftsorientierter Flughafenführer",
    aiSearchReady: "Für KI-Suche optimierter Reiseführer",
    editorialNote:
      "Planungshinweis: Regeln, Versicherungsbedingungen, Sicherheitslage, Transportpreise und Netzabdeckung können sich ändern. Prüfen Sie wichtige Details vor der Buchung offiziell.",
  },
  es: {
    shortAnswer: "Respuesta rápida",
    quickSnapshot: "Resumen de planificación",
    destinationSnapshot: "Resumen del destino",
    relatedPlanningLinks: "Enlaces de planificación",
    faq: "Preguntas frecuentes",
    from: "Desde",
    to: "A",
    localCurrency: "Moneda local",
    originCurrency: "Moneda de origen",
    perPersonDay: "por persona / día",
    planWithRya: "Planificar con Rya",
    airportArrivalGuide: "Guía de llegada al aeropuerto",
    aiSearchReady: "Guía optimizada para búsqueda con IA",
    editorialNote:
      "Nota de planificación: las normas, seguros, seguridad, precios de transporte y cobertura móvil pueden cambiar. Confirma los detalles críticos con fuentes oficiales antes de reservar.",
  },
  it: {
    shortAnswer: "Risposta rapida",
    quickSnapshot: "Sintesi di pianificazione",
    destinationSnapshot: "Panoramica destinazione",
    relatedPlanningLinks: "Link di pianificazione",
    faq: "Domande frequenti",
    from: "Da",
    to: "A",
    localCurrency: "Valuta locale",
    originCurrency: "Valuta di partenza",
    perPersonDay: "per persona / giorno",
    planWithRya: "Pianifica con Rya",
    airportArrivalGuide: "Guida arrivo aeroporto",
    aiSearchReady: "Guida ottimizzata per ricerca IA",
    editorialNote:
      "Nota di pianificazione: regole, assicurazioni, sicurezza, prezzi dei trasporti e copertura mobile possono cambiare. Verifica i dettagli critici con fonti ufficiali.",
  },
  pt: {
    shortAnswer: "Resposta rápida",
    quickSnapshot: "Resumo de planejamento",
    destinationSnapshot: "Resumo do destino",
    relatedPlanningLinks: "Links de planejamento",
    faq: "Perguntas frequentes",
    from: "De",
    to: "Para",
    localCurrency: "Moeda local",
    originCurrency: "Moeda de origem",
    perPersonDay: "por pessoa / dia",
    planWithRya: "Planejar com Rya",
    airportArrivalGuide: "Guia de chegada ao aeroporto",
    aiSearchReady: "Guia otimizado para busca com IA",
    editorialNote:
      "Nota de planejamento: regras, seguros, segurança, preços de transporte e cobertura móvel podem mudar. Confirme detalhes importantes com fontes oficiais antes de reservar.",
  },
  ko: {
    shortAnswer: "빠른 답변",
    quickSnapshot: "여행 계획 요약",
    destinationSnapshot: "목적지 요약",
    relatedPlanningLinks: "관련 계획 링크",
    faq: "자주 묻는 질문",
    from: "출발",
    to: "도착",
    localCurrency: "현지 통화",
    originCurrency: "출발지 통화",
    perPersonDay: "1인 / 1일",
    planWithRya: "Rya와 계획하기",
    airportArrivalGuide: "공항 도착 가이드",
    aiSearchReady: "AI 검색 최적화 여행 가이드",
    editorialNote:
      "여행 규정, 보험 조건, 안전 상황, 교통 요금, 모바일 커버리지는 변동될 수 있습니다. 예약 전 중요한 정보는 공식 채널에서 확인하세요.",
  },
  ja: {
    shortAnswer: "要点",
    quickSnapshot: "旅行計画の概要",
    destinationSnapshot: "目的地の概要",
    relatedPlanningLinks: "関連する計画リンク",
    faq: "よくある質問",
    from: "出発地",
    to: "目的地",
    localCurrency: "現地通貨",
    originCurrency: "出発地の通貨",
    perPersonDay: "1人 / 1日",
    planWithRya: "Ryaで計画する",
    airportArrivalGuide: "空港到着ガイド",
    aiSearchReady: "AI検索向け旅行ガイド",
    editorialNote:
      "旅行規則、保険条件、安全状況、交通料金、通信環境は変わることがあります。予約前に重要事項を公式情報で確認してください。",
  },
  zh: {
    shortAnswer: "简短回答",
    quickSnapshot: "行程规划摘要",
    destinationSnapshot: "目的地概览",
    relatedPlanningLinks: "相关规划链接",
    faq: "常见问题",
    from: "出发地",
    to: "目的地",
    localCurrency: "当地货币",
    originCurrency: "出发地货币",
    perPersonDay: "每人 / 每日",
    planWithRya: "用 Rya 规划",
    airportArrivalGuide: "机场抵达指南",
    aiSearchReady: "AI 搜索优化旅行指南",
    editorialNote:
      "规划提示：旅行规定、保险条款、安全情况、交通价格和网络覆盖可能变化。预订前请通过官方渠道确认重要信息。",
  },
  nl: {
    shortAnswer: "Kort antwoord",
    quickSnapshot: "Planningssamenvatting",
    destinationSnapshot: "Bestemmingsoverzicht",
    relatedPlanningLinks: "Gerelateerde planningslinks",
    faq: "Veelgestelde vragen",
    from: "Vanaf",
    to: "Naar",
    localCurrency: "Lokale valuta",
    originCurrency: "Valuta vertrekpunt",
    perPersonDay: "per persoon / dag",
    planWithRya: "Plan met Rya",
    airportArrivalGuide: "Aankomstgerichte luchthavengids",
    aiSearchReady: "AI-zoekklare reisgids",
    editorialNote:
      "Planningsnotitie: regels, verzekeringsvoorwaarden, veiligheid, vervoersprijzen en mobiele dekking kunnen veranderen. Controleer cruciale details officieel vóór boeking.",
  },
  tr: {
    shortAnswer: "Kısa cevap",
    quickSnapshot: "Hızlı plan özeti",
    destinationSnapshot: "Destinasyon özeti",
    relatedPlanningLinks: "İlgili planlama linkleri",
    faq: "Sık sorulan sorular",
    from: "Nereden",
    to: "Nereye",
    localCurrency: "Yerel para birimi",
    originCurrency: "Çıkış para birimi",
    perPersonDay: "kişi / gün",
    planWithRya: "Rya ile planla",
    airportArrivalGuide: "Varış odaklı havalimanı rehberi",
    aiSearchReady: "AI araması için hazır seyahat rehberi",
    editorialNote:
      "Planlama notu: kurallar, sigorta şartları, güvenlik durumu, ulaşım fiyatları ve mobil kapsama değişebilir. Rezervasyon öncesi kritik bilgileri resmi kaynaklardan doğrulayın.",
  },
  hi: {
    shortAnswer: "संक्षिप्त उत्तर",
    quickSnapshot: "त्वरित योजना सारांश",
    destinationSnapshot: "गंतव्य सारांश",
    relatedPlanningLinks: "संबंधित योजना लिंक",
    faq: "अक्सर पूछे जाने वाले प्रश्न",
    from: "से",
    to: "तक",
    localCurrency: "स्थानीय मुद्रा",
    originCurrency: "प्रस्थान मुद्रा",
    perPersonDay: "प्रति व्यक्ति / दिन",
    planWithRya: "Rya के साथ योजना बनाएं",
    airportArrivalGuide: "आगमन-केंद्रित एयरपोर्ट गाइड",
    aiSearchReady: "AI खोज के लिए तैयार यात्रा गाइड",
    editorialNote:
      "योजना नोट: नियम, बीमा शर्तें, सुरक्षा स्थिति, परिवहन कीमतें और मोबाइल कवरेज बदल सकते हैं। बुकिंग से पहले महत्वपूर्ण जानकारी आधिकारिक स्रोतों से जांचें।",
  },
  id: {
    shortAnswer: "Jawaban singkat",
    quickSnapshot: "Ringkasan rencana cepat",
    destinationSnapshot: "Ringkasan destinasi",
    relatedPlanningLinks: "Tautan perencanaan terkait",
    faq: "Pertanyaan umum",
    from: "Dari",
    to: "Ke",
    localCurrency: "Mata uang lokal",
    originCurrency: "Mata uang asal",
    perPersonDay: "per orang / hari",
    planWithRya: "Rencanakan dengan Rya",
    airportArrivalGuide: "Panduan kedatangan bandara",
    aiSearchReady: "Panduan perjalanan siap pencarian AI",
    editorialNote:
      "Catatan perencanaan: aturan, syarat asuransi, keamanan, harga transportasi, dan cakupan seluler dapat berubah. Periksa detail penting melalui sumber resmi sebelum memesan.",
  },
  ru: {
    shortAnswer: "Краткий ответ",
    quickSnapshot: "Краткий план",
    destinationSnapshot: "Обзор направления",
    relatedPlanningLinks: "Связанные ссылки",
    faq: "Частые вопросы",
    from: "Из",
    to: "В",
    localCurrency: "Местная валюта",
    originCurrency: "Валюта отправления",
    perPersonDay: "на человека / день",
    planWithRya: "Планировать с Rya",
    airportArrivalGuide: "Гид по прибытию в аэропорт",
    aiSearchReady: "Гид для AI-поиска",
    editorialNote:
      "Примечание: правила, страховка, безопасность, транспортные цены и мобильная связь могут меняться. Перед бронированием проверяйте важные детали в официальных источниках.",
  },
  pl: {
    shortAnswer: "Krótka odpowiedź",
    quickSnapshot: "Szybki plan",
    destinationSnapshot: "Przegląd kierunku",
    relatedPlanningLinks: "Powiązane linki",
    faq: "Najczęstsze pytania",
    from: "Z",
    to: "Do",
    localCurrency: "Waluta lokalna",
    originCurrency: "Waluta wyjazdu",
    perPersonDay: "osoba / dzień",
    planWithRya: "Planuj z Rya",
    airportArrivalGuide: "Przewodnik po przylocie",
    aiSearchReady: "Przewodnik gotowy pod wyszukiwanie AI",
    editorialNote:
      "Uwaga: przepisy, warunki ubezpieczenia, bezpieczeństwo, ceny transportu i zasięg mogą się zmieniać. Przed rezerwacją sprawdź kluczowe informacje oficjalnie.",
  },
  th: {
    shortAnswer: "คำตอบสั้น",
    quickSnapshot: "สรุปแผนอย่างรวดเร็ว",
    destinationSnapshot: "สรุปจุดหมาย",
    relatedPlanningLinks: "ลิงก์วางแผนที่เกี่ยวข้อง",
    faq: "คำถามที่พบบ่อย",
    from: "จาก",
    to: "ถึง",
    localCurrency: "สกุลเงินท้องถิ่น",
    originCurrency: "สกุลเงินต้นทาง",
    perPersonDay: "ต่อคน / วัน",
    planWithRya: "วางแผนกับ Rya",
    airportArrivalGuide: "คู่มือเดินทางจากสนามบิน",
    aiSearchReady: "คู่มือเที่ยวพร้อมสำหรับการค้นหา AI",
    editorialNote:
      "หมายเหตุ: กฎการเดินทาง ประกัน ความปลอดภัย ราคาเดินทาง และสัญญาณมือถืออาจเปลี่ยนได้ โปรดตรวจสอบข้อมูลสำคัญจากแหล่งทางการก่อนจอง.",
  },
  vi: {
    shortAnswer: "Trả lời nhanh",
    quickSnapshot: "Tóm tắt kế hoạch",
    destinationSnapshot: "Tóm tắt điểm đến",
    relatedPlanningLinks: "Liên kết lập kế hoạch",
    faq: "Câu hỏi thường gặp",
    from: "Từ",
    to: "Đến",
    localCurrency: "Tiền tệ địa phương",
    originCurrency: "Tiền tệ nơi đi",
    perPersonDay: "mỗi người / ngày",
    planWithRya: "Lên kế hoạch với Rya",
    airportArrivalGuide: "Hướng dẫn đến nơi từ sân bay",
    aiSearchReady: "Hướng dẫn du lịch tối ưu cho AI Search",
    editorialNote:
      "Lưu ý: quy định, bảo hiểm, an toàn, giá di chuyển và phủ sóng di động có thể thay đổi. Hãy kiểm tra thông tin quan trọng từ nguồn chính thức trước khi đặt.",
  },
  ms: {
    shortAnswer: "Jawapan ringkas",
    quickSnapshot: "Ringkasan perancangan",
    destinationSnapshot: "Ringkasan destinasi",
    relatedPlanningLinks: "Pautan perancangan berkaitan",
    faq: "Soalan lazim",
    from: "Dari",
    to: "Ke",
    localCurrency: "Mata wang tempatan",
    originCurrency: "Mata wang asal",
    perPersonDay: "seorang / hari",
    planWithRya: "Rancang dengan Rya",
    airportArrivalGuide: "Panduan ketibaan lapangan terbang",
    aiSearchReady: "Panduan perjalanan sedia carian AI",
    editorialNote:
      "Nota: peraturan, insurans, keselamatan, harga pengangkutan dan liputan mudah alih boleh berubah. Semak butiran penting melalui sumber rasmi sebelum menempah.",
  },
  sv: {
    shortAnswer: "Kort svar",
    quickSnapshot: "Snabb planeringsbild",
    destinationSnapshot: "Översikt över resmålet",
    relatedPlanningLinks: "Relaterade planeringslänkar",
    faq: "Vanliga frågor",
    from: "Från",
    to: "Till",
    localCurrency: "Lokal valuta",
    originCurrency: "Avresevaluta",
    perPersonDay: "per person / dag",
    planWithRya: "Planera med Rya",
    airportArrivalGuide: "Ankomstguide för flygplatsen",
    aiSearchReady: "AI-sökanpassad reseguide",
    editorialNote:
      "Planeringsnotis: regler, försäkringar, säkerhet, transportpriser och mobiltäckning kan ändras. Kontrollera viktiga detaljer officiellt före bokning.",
  },
  no: {
    shortAnswer: "Kort svar",
    quickSnapshot: "Rask planoversikt",
    destinationSnapshot: "Destinasjonsoversikt",
    relatedPlanningLinks: "Relaterte planlenker",
    faq: "Vanlige spørsmål",
    from: "Fra",
    to: "Til",
    localCurrency: "Lokal valuta",
    originCurrency: "Avreisevaluta",
    perPersonDay: "per person / dag",
    planWithRya: "Planlegg med Rya",
    airportArrivalGuide: "Ankomstguide for flyplass",
    aiSearchReady: "AI-søkeklar reiseguide",
    editorialNote:
      "Planleggingsnotat: regler, forsikring, sikkerhet, transportpriser og mobildekning kan endre seg. Sjekk viktige detaljer offisielt før bestilling.",
  },
  da: {
    shortAnswer: "Kort svar",
    quickSnapshot: "Hurtigt planoverblik",
    destinationSnapshot: "Destinationsoversigt",
    relatedPlanningLinks: "Relaterede planlægningslinks",
    faq: "Ofte stillede spørgsmål",
    from: "Fra",
    to: "Til",
    localCurrency: "Lokal valuta",
    originCurrency: "Afrejsevaluta",
    perPersonDay: "per person / dag",
    planWithRya: "Planlæg med Rya",
    airportArrivalGuide: "Ankomstguide til lufthavn",
    aiSearchReady: "AI-søgeklar rejseguide",
    editorialNote:
      "Planlægningsnote: regler, forsikring, sikkerhed, transportpriser og mobildækning kan ændre sig. Tjek vigtige detaljer officielt før booking.",
  },
};

export function seoCopy(locale: Locale): SeoCopy {
  return { ...EN, ...(COPIES[locale] ?? {}) };
}
