import { BUDGET_PAGES, COMPARISON_PAGES, DESTINATION_SLUGS } from "@/lib/seo-destinations";
import { ROUTE_SLUGS } from "@/lib/route-pairs";

export const metadata = { title: "Content" };

const contentFiles = [
  {
    type: "Blog",
    path: "/src/content/blog/",
    notes: "Static MDX posts",
  },
  {
    type: "Homepage i18n",
    path: "/src/i18n/dictionaries/",
    notes: "AR + EN JSON dictionaries",
  },
  {
    type: "System prompt",
    path: "/src/lib/ai/prompts/raya-system.ts",
    notes: "Raya's AI persona",
  },
  {
    type: "AI schemas",
    path: "/src/lib/ai/schemas/",
    notes: "Intent + intelligence schemas",
  },
] as const;

const seoInventory = [
  { label: "Destination hubs", count: DESTINATION_SLUGS.length * 2, note: "Arabic + English destination guides" },
  { label: "Hotel readiness pages", count: DESTINATION_SLUGS.length * 2, note: "Temporary stay guides until hotel API is connected" },
  { label: "Season pages", count: DESTINATION_SLUGS.length * 2, note: "Best time to visit pages" },
  { label: "Visa pages", count: DESTINATION_SLUGS.length * 2, note: "Visa intent pages" },
  { label: "Budget pages", count: BUDGET_PAGES.length * 2, note: "Trip cost and budget intent pages" },
  { label: "Comparison pages", count: COMPARISON_PAGES.length * 2, note: "Destination-vs-destination pages" },
  { label: "Flight route pages", count: ROUTE_SLUGS.length * 2, note: "High-intent route pages" },
];

export default function ContentPage() {
  return (
    <div className="min-h-screen bg-[#08080d] px-6 py-8 space-y-8">
      {/* Header */}
      <div>
        <h1 className="text-white text-2xl font-semibold tracking-tight">Content &amp; Destinations</h1>
        <p className="text-white/40 text-sm mt-1">Content sources, file locations, and configuration</p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        {seoInventory.slice(0, 4).map((item) => (
          <div key={item.label} className="rounded-2xl border border-white/[0.06] bg-white/[0.03] p-5">
            <p className="text-xs text-white/35">{item.label}</p>
            <p className="mt-2 text-2xl font-semibold text-white">{item.count.toLocaleString()}</p>
            <p className="mt-1 text-xs leading-5 text-white/35">{item.note}</p>
          </div>
        ))}
      </div>

      {/* Content Sources Card */}
      <div className="rounded-2xl border border-white/[0.06] bg-white/[0.03] p-6 space-y-5">
        <h2 className="text-sm font-semibold uppercase tracking-[0.15em] text-white/60">
          Content Sources
        </h2>

        <div className="space-y-4">
          {/* Destination descriptions */}
          <div className="flex gap-4 items-start">
            <div className="mt-0.5 h-2 w-2 rounded-full bg-blue-400 shrink-0" />
            <div>
              <p className="text-sm font-medium text-white/80">Destination descriptions</p>
              <p className="text-sm text-white/45 mt-0.5">
                Generated by AI via OpenAI{" "}
                <code className="text-white/60 bg-white/[0.06] px-1.5 py-0.5 rounded text-xs">
                  gpt-4o-mini
                </code>
                . Cached in Supabase{" "}
                <code className="text-white/60 bg-white/[0.06] px-1.5 py-0.5 rounded text-xs">
                  destination_intel
                </code>{" "}
                table.
              </p>
            </div>
          </div>

          {/* Blog posts */}
          <div className="flex gap-4 items-start">
            <div className="mt-0.5 h-2 w-2 rounded-full bg-purple-400 shrink-0" />
            <div>
              <p className="text-sm font-medium text-white/80">Blog posts</p>
              <p className="text-sm text-white/45 mt-0.5">
                Static MDX files in{" "}
                <code className="text-white/60 bg-white/[0.06] px-1.5 py-0.5 rounded text-xs">
                  /src/content/blog/
                </code>
              </p>
            </div>
          </div>

          {/* Homepage copy */}
          <div className="flex gap-4 items-start">
            <div className="mt-0.5 h-2 w-2 rounded-full bg-emerald-400 shrink-0" />
            <div>
              <p className="text-sm font-medium text-white/80">Homepage copy</p>
              <p className="text-sm text-white/45 mt-0.5">
                Localized via{" "}
                <code className="text-white/60 bg-white/[0.06] px-1.5 py-0.5 rounded text-xs">
                  /src/i18n/dictionaries/[locale].json
                </code>
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="rounded-2xl border border-white/[0.06] bg-white/[0.03] overflow-hidden">
        <div className="px-6 py-4 border-b border-white/[0.06]">
          <h2 className="text-sm font-semibold uppercase tracking-[0.15em] text-white/60">
            SEO Page Inventory
          </h2>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-white/[0.06]">
                <th className="px-6 py-3 text-left text-[11px] font-medium uppercase tracking-[0.15em] text-white/30">Cluster</th>
                <th className="px-6 py-3 text-right text-[11px] font-medium uppercase tracking-[0.15em] text-white/30">Pages</th>
                <th className="px-6 py-3 text-left text-[11px] font-medium uppercase tracking-[0.15em] text-white/30">Purpose</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/[0.04]">
              {seoInventory.map((item) => (
                <tr key={item.label} className="hover:bg-white/[0.02] transition-colors">
                  <td className="px-6 py-3.5 text-white/70 font-medium">{item.label}</td>
                  <td className="px-6 py-3.5 text-right tabular-nums text-white/60">{item.count.toLocaleString()}</td>
                  <td className="px-6 py-3.5 text-white/40 text-xs">{item.note}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Key Content Files Table */}
      <div className="rounded-2xl border border-white/[0.06] bg-white/[0.03] overflow-hidden">
        <div className="px-6 py-4 border-b border-white/[0.06]">
          <h2 className="text-sm font-semibold uppercase tracking-[0.15em] text-white/60">
            Key Content Files
          </h2>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-white/[0.06]">
                <th className="px-6 py-3 text-left text-[11px] font-medium uppercase tracking-[0.15em] text-white/30">
                  Type
                </th>
                <th className="px-6 py-3 text-left text-[11px] font-medium uppercase tracking-[0.15em] text-white/30">
                  Path
                </th>
                <th className="px-6 py-3 text-left text-[11px] font-medium uppercase tracking-[0.15em] text-white/30">
                  Notes
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/[0.04]">
              {contentFiles.map((file) => (
                <tr key={file.path} className="hover:bg-white/[0.02] transition-colors">
                  <td className="px-6 py-3.5 text-white/70 font-medium whitespace-nowrap">
                    {file.type}
                  </td>
                  <td className="px-6 py-3.5">
                    <code className="text-blue-400/80 text-xs bg-blue-500/[0.08] px-2 py-1 rounded font-mono">
                      {file.path}
                    </code>
                  </td>
                  <td className="px-6 py-3.5 text-white/40 text-xs">
                    {file.notes}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
