-- Saved trip plans generated by the GoTripza trip planner.
-- Uses auth.users directly so plans follow the current Supabase Auth setup.

create table if not exists public.trip_plans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  locale text not null default 'ar' check (locale in ('ar', 'en')),
  origin text,
  destination text not null,
  days int not null default 1,
  travelers int not null default 1,
  budget numeric,
  currency text not null default 'SAR',
  trip_type text,
  plan jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists trip_plans_user_created_idx
  on public.trip_plans (user_id, created_at desc);

alter table public.trip_plans enable row level security;

drop policy if exists "trip_plans_self_read" on public.trip_plans;
drop policy if exists "trip_plans_self_insert" on public.trip_plans;
drop policy if exists "trip_plans_self_update" on public.trip_plans;
drop policy if exists "trip_plans_self_delete" on public.trip_plans;

create policy "trip_plans_self_read"
  on public.trip_plans for select
  using (auth.uid() = user_id);

create policy "trip_plans_self_insert"
  on public.trip_plans for insert
  with check (auth.uid() = user_id);

create policy "trip_plans_self_update"
  on public.trip_plans for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "trip_plans_self_delete"
  on public.trip_plans for delete
  using (auth.uid() = user_id);

drop trigger if exists trip_plans_touch on public.trip_plans;
create trigger trip_plans_touch before update on public.trip_plans
  for each row execute function public.touch_updated_at();
